import { DEMO_AGENCY_ID } from "@/contexts/DemoContext";
import { format, addHours, subDays, addDays, setHours, setMinutes, startOfWeek } from "date-fns";

const today = new Date();
const todayStr = format(today, "yyyy-MM-dd");

// Helper to make ISO timestamps for today
function todayAt(hour: number, min = 0) {
  return setMinutes(setHours(today, hour), min).toISOString();
}
function dayAt(daysOffset: number, hour: number, min = 0) {
  const d = addDays(today, daysOffset);
  return setMinutes(setHours(d, hour), min).toISOString();
}

// ── Demo Customers ─────────────────────────────────────
export const demoCustomers = [
  {
    id: "demo-cust-1",
    agency_id: DEMO_AGENCY_ID,
    name: "Valley Medical Center",
    contact_name: "Dr. Amanda Foster",
    contact_email: "afoster@valleymed.org",
    contact_phone: "(555) 401-2000",
    billing_email: "billing@valleymed.org",
    notes: "Preferred vendor. Monthly invoicing.",
    is_active: true,
    created_at: subDays(today, 90).toISOString(),
    updated_at: subDays(today, 5).toISOString(),
  },
  {
    id: "demo-cust-2",
    agency_id: DEMO_AGENCY_ID,
    name: "Johnson & Associates Law",
    contact_name: "Mark Johnson",
    contact_email: "mjohnson@jalegal.com",
    contact_phone: "(555) 402-3000",
    billing_email: "ap@jalegal.com",
    notes: "Requires certified interpreters only.",
    is_active: true,
    created_at: subDays(today, 120).toISOString(),
    updated_at: subDays(today, 12).toISOString(),
  },
  {
    id: "demo-cust-3",
    agency_id: DEMO_AGENCY_ID,
    name: "City School District",
    contact_name: "Patricia Gomez",
    contact_email: "pgomez@citysd.edu",
    contact_phone: "(555) 403-4000",
    billing_email: "finance@citysd.edu",
    notes: "IEP and parent conferences. High volume Sept–May.",
    is_active: true,
    created_at: subDays(today, 200).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
  },
  {
    id: "demo-cust-4",
    agency_id: DEMO_AGENCY_ID,
    name: "County Superior Court",
    contact_name: "Judge Rebecca Torres",
    contact_email: "rtorres@countycourt.gov",
    contact_phone: "(555) 404-5000",
    billing_email: "finance@countycourt.gov",
    notes: "Legal proceedings. All interpreters must be court-certified.",
    is_active: true,
    created_at: subDays(today, 365).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-cust-5",
    agency_id: DEMO_AGENCY_ID,
    name: "Sunrise Community Health",
    contact_name: "Nurse Rita Patel",
    contact_email: "rpatel@sunrisech.org",
    contact_phone: "(555) 405-6000",
    billing_email: "billing@sunrisech.org",
    notes: "",
    is_active: false,
    created_at: subDays(today, 150).toISOString(),
    updated_at: subDays(today, 30).toISOString(),
  },
];

// ── Demo Interpreters (profiles with user_roles join shape) ──
export const demoInterpreters = [
  {
    id: "demo-interp-1",
    agency_id: DEMO_AGENCY_ID,
    first_name: "Carlos",
    last_name: "Rivera",
    email: "carlos@interpreter.com",
    phone: "(555) 300-0001",
    avatar_url: null,
    is_active: true,
    created_at: subDays(today, 180).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    user_roles: [{ role: "interpreter" }],
  },
  {
    id: "demo-interp-2",
    agency_id: DEMO_AGENCY_ID,
    first_name: "Mei",
    last_name: "Wong",
    email: "mei.wong@interpreter.com",
    phone: "(555) 300-0002",
    avatar_url: null,
    is_active: true,
    created_at: subDays(today, 160).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
    user_roles: [{ role: "interpreter" }],
  },
  {
    id: "demo-interp-3",
    agency_id: DEMO_AGENCY_ID,
    first_name: "Fatima",
    last_name: "Al-Hassan",
    email: "fatima.alhassan@interpreter.com",
    phone: "(555) 300-0003",
    avatar_url: null,
    is_active: true,
    created_at: subDays(today, 140).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    user_roles: [{ role: "interpreter" }],
  },
  {
    id: "demo-interp-4",
    agency_id: DEMO_AGENCY_ID,
    first_name: "Andrei",
    last_name: "Volkov",
    email: "andrei.volkov@interpreter.com",
    phone: "(555) 300-0004",
    avatar_url: null,
    is_active: true,
    created_at: subDays(today, 100).toISOString(),
    updated_at: subDays(today, 7).toISOString(),
    user_roles: [{ role: "interpreter" }],
  },
  {
    id: "demo-interp-5",
    agency_id: DEMO_AGENCY_ID,
    first_name: "Yuki",
    last_name: "Tanaka",
    email: "yuki.tanaka@interpreter.com",
    phone: "(555) 300-0005",
    avatar_url: null,
    is_active: true,
    created_at: subDays(today, 80).toISOString(),
    updated_at: subDays(today, 5).toISOString(),
    user_roles: [{ role: "interpreter" }],
  },
];

// ── Demo Languages ──────────────────────────────────────
export const demoLanguages = [
  { id: "demo-lang-1", name: "Spanish", code: "es" },
  { id: "demo-lang-2", name: "Mandarin", code: "zh" },
  { id: "demo-lang-3", name: "Arabic", code: "ar" },
  { id: "demo-lang-4", name: "Russian", code: "ru" },
  { id: "demo-lang-5", name: "Japanese", code: "ja" },
  { id: "demo-lang-6", name: "Vietnamese", code: "vi" },
  { id: "demo-lang-7", name: "Portuguese", code: "pt" },
  { id: "demo-lang-8", name: "ASL (American Sign Language)", code: "ase" },
];

// ── Demo Locations ──────────────────────────────────────
export const demoLocations = [
  {
    id: "demo-loc-1",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-1",
    name: "Valley Medical – Main Campus",
    address_line1: "1200 Health Blvd",
    address_line2: null,
    city: "Springfield",
    state: "IL",
    zip_code: "62704",
    phone: "(555) 401-2001",
    navigation_instructions: "Enter through East entrance, check in at front desk.",
    created_at: subDays(today, 90).toISOString(),
  },
  {
    id: "demo-loc-2",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-2",
    name: "Johnson & Associates – Downtown Office",
    address_line1: "500 Main St, Suite 300",
    address_line2: null,
    city: "Springfield",
    state: "IL",
    zip_code: "62701",
    phone: "(555) 402-3001",
    navigation_instructions: "3rd floor, Suite 300. Parking in rear lot.",
    created_at: subDays(today, 120).toISOString(),
  },
  {
    id: "demo-loc-3",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-3",
    name: "Lincoln Elementary School",
    address_line1: "850 Oak Ave",
    address_line2: null,
    city: "Springfield",
    state: "IL",
    zip_code: "62703",
    phone: "(555) 403-4001",
    navigation_instructions: "Report to main office upon arrival.",
    created_at: subDays(today, 200).toISOString(),
  },
  {
    id: "demo-loc-4",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-4",
    name: "County Courthouse – Room 214",
    address_line1: "100 Court Square",
    address_line2: "Room 214",
    city: "Springfield",
    state: "IL",
    zip_code: "62701",
    phone: "(555) 404-5001",
    navigation_instructions: "Security screening required. Arrive 15 min early.",
    created_at: subDays(today, 365).toISOString(),
  },
];

// ── Demo Appointments ───────────────────────────────────
// Shaped like the Supabase join query: includes nested customers, locations, languages, interpreter, requester
export const demoAppointments = [
  {
    id: "demo-appt-0001",
    agency_id: DEMO_AGENCY_ID,
    title: "Medical Consultation",
    description: "Patient follow-up visit",
    status: "interpreter_assigned",
    modality: "on_site",
    scheduled_start: todayAt(8, 30),
    scheduled_end: todayAt(9, 30),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-1",
    interpreter_id: "demo-interp-1",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Patient prefers female interpreter if available.",
    interpreter_notes: null,
    agency_notes: "Confirmed with department head",
    interpreter_notes_history: null,
    custom_fields: { include_mileage: true, include_travel: false },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Spanish", code: "es" },
    interpreter: { first_name: "Carlos", last_name: "Rivera" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0002",
    agency_id: DEMO_AGENCY_ID,
    title: "Legal Deposition",
    description: "Witness deposition for civil case #2024-1847",
    status: "interpreter_confirmed",
    modality: "on_site",
    scheduled_start: todayAt(10, 0),
    scheduled_end: todayAt(12, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-2",
    location_id: "demo-loc-2",
    language_id: "demo-lang-2",
    interpreter_id: "demo-interp-2",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Court-certified interpreter required.",
    interpreter_notes: "Reviewed case materials. Ready.",
    agency_notes: null,
    interpreter_notes_history: null,
    custom_fields: { include_mileage: false, include_travel: true },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    customers: { name: "Johnson & Associates Law" },
    locations: { name: "Johnson & Associates – Downtown Office", address_line1: "500 Main St, Suite 300", city: "Springfield", state: "IL", zip_code: "62701" },
    languages: { name: "Mandarin", code: "zh" },
    interpreter: { first_name: "Mei", last_name: "Wong" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0003",
    agency_id: DEMO_AGENCY_ID,
    title: "IEP Meeting",
    description: "Annual IEP review for student",
    status: "requested",
    modality: "on_site",
    scheduled_start: todayAt(13, 0),
    scheduled_end: todayAt(14, 30),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-3",
    location_id: "demo-loc-3",
    language_id: "demo-lang-3",
    interpreter_id: null,
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Parents speak Arabic. Please confirm dialect.",
    interpreter_notes: null,
    agency_notes: null,
    interpreter_notes_history: null,
    custom_fields: null,
    assignment_method: null,
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: true,
    created_at: subDays(today, 1).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield", state: "IL", zip_code: "62703" },
    languages: { name: "Arabic", code: "ar" },
    interpreter: null,
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0004",
    agency_id: DEMO_AGENCY_ID,
    title: "Court Hearing",
    description: "Criminal case hearing – Judge Torres presiding",
    status: "in_progress",
    modality: "on_site",
    scheduled_start: todayAt(9, 0),
    scheduled_end: todayAt(11, 0),
    actual_start: todayAt(9, 5),
    actual_end: null,
    customer_id: "demo-cust-4",
    location_id: "demo-loc-4",
    language_id: "demo-lang-4",
    interpreter_id: "demo-interp-4",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: null,
    interpreter_notes: "Arrived early. Security screening complete.",
    agency_notes: "High-profile case. Ensure backup interpreter on standby.",
    interpreter_notes_history: null,
    custom_fields: { include_mileage: true, include_travel: true },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 3).toISOString(),
    updated_at: today.toISOString(),
    customers: { name: "County Superior Court" },
    locations: { name: "County Courthouse – Room 214", address_line1: "100 Court Square", city: "Springfield", state: "IL", zip_code: "62701" },
    languages: { name: "Russian", code: "ru" },
    interpreter: { first_name: "Andrei", last_name: "Volkov" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0005",
    agency_id: DEMO_AGENCY_ID,
    title: "Patient Intake",
    description: "New patient registration assistance",
    status: "completed",
    modality: "on_site",
    scheduled_start: dayAt(-1, 14, 0),
    scheduled_end: dayAt(-1, 15, 0),
    actual_start: dayAt(-1, 14, 5),
    actual_end: dayAt(-1, 15, 10),
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-6",
    interpreter_id: "demo-interp-5",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Patient needs Vietnamese.",
    interpreter_notes: "Completed without issues.",
    agency_notes: null,
    interpreter_notes_history: null,
    custom_fields: { include_mileage: false, include_travel: false },
    assignment_method: "availability",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 4).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Vietnamese", code: "vi" },
    interpreter: { first_name: "Yuki", last_name: "Tanaka" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0006",
    agency_id: DEMO_AGENCY_ID,
    title: "Parent-Teacher Conference",
    description: "End of semester parent meeting",
    status: "interpreter_assigned",
    modality: "on_site",
    scheduled_start: dayAt(1, 15, 0),
    scheduled_end: dayAt(1, 16, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-3",
    location_id: "demo-loc-3",
    language_id: "demo-lang-1",
    interpreter_id: "demo-interp-1",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: null,
    interpreter_notes: null,
    agency_notes: null,
    interpreter_notes_history: null,
    custom_fields: null,
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield", state: "IL", zip_code: "62703" },
    languages: { name: "Spanish", code: "es" },
    interpreter: { first_name: "Carlos", last_name: "Rivera" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0007",
    agency_id: DEMO_AGENCY_ID,
    title: "Emergency Room Visit",
    description: "ER patient needs language assistance",
    status: "requested_last_minute",
    modality: "on_site",
    scheduled_start: dayAt(0, 16, 0),
    scheduled_end: dayAt(0, 17, 30),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-7",
    interpreter_id: null,
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Urgent – assign ASAP.",
    interpreter_notes: null,
    agency_notes: "Last-minute request. Check all available interpreters.",
    interpreter_notes_history: null,
    custom_fields: { is_last_minute: true },
    assignment_method: null,
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: true,
    created_at: todayAt(15, 30),
    updated_at: todayAt(15, 30),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Portuguese", code: "pt" },
    interpreter: null,
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  {
    id: "demo-appt-0008",
    agency_id: DEMO_AGENCY_ID,
    title: "Witness Interview",
    description: "Pre-trial witness preparation",
    status: "cancelled",
    modality: "on_site",
    scheduled_start: dayAt(-2, 9, 0),
    scheduled_end: dayAt(-2, 10, 30),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-2",
    location_id: "demo-loc-2",
    language_id: "demo-lang-5",
    interpreter_id: "demo-interp-5",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: null,
    interpreter_notes: null,
    agency_notes: null,
    interpreter_notes_history: null,
    custom_fields: null,
    assignment_method: "manual",
    cancellation_reason: "Client rescheduled.",
    cancelled_at: subDays(today, 3).toISOString(),
    is_self_claimable: false,
    created_at: subDays(today, 7).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
    customers: { name: "Johnson & Associates Law" },
    locations: { name: "Johnson & Associates – Downtown Office", address_line1: "500 Main St, Suite 300", city: "Springfield", state: "IL", zip_code: "62701" },
    languages: { name: "Japanese", code: "ja" },
    interpreter: { first_name: "Yuki", last_name: "Tanaka" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  // v3 statuses: last-minute assigned
  {
    id: "demo-appt-0009",
    agency_id: DEMO_AGENCY_ID,
    title: "Urgent Clinic Visit",
    description: "Walk-in patient needing immediate assistance",
    status: "interpreter_assigned_last_minute",
    modality: "on_site",
    scheduled_start: todayAt(14, 0),
    scheduled_end: todayAt(15, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-1",
    interpreter_id: "demo-interp-3",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Patient arrived at ER, needs Spanish interpreter.",
    interpreter_notes: null,
    agency_notes: "Last-minute assignment. Fatima was available.",
    interpreter_notes_history: null,
    custom_fields: { is_last_minute: true, include_mileage: true, include_travel: false },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: todayAt(13, 30),
    updated_at: todayAt(13, 45),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Spanish", code: "es" },
    interpreter: { first_name: "Fatima", last_name: "Al-Hassan" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  // v3: completed_last_minute
  {
    id: "demo-appt-0010",
    agency_id: DEMO_AGENCY_ID,
    title: "ER Triage – Last Minute",
    description: "Emergency triage interpretation",
    status: "completed_last_minute",
    modality: "on_site",
    scheduled_start: dayAt(-1, 18, 0),
    scheduled_end: dayAt(-1, 19, 0),
    actual_start: dayAt(-1, 18, 5),
    actual_end: dayAt(-1, 19, 10),
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-3",
    interpreter_id: "demo-interp-3",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Emergency case.",
    interpreter_notes: "Patient stabilized. Completed.",
    agency_notes: "Last-minute premium applied.",
    interpreter_notes_history: null,
    custom_fields: { is_last_minute: true, include_mileage: false, include_travel: false },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: dayAt(-1, 17, 30),
    updated_at: dayAt(-1, 19, 10),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Arabic", code: "ar" },
    interpreter: { first_name: "Fatima", last_name: "Al-Hassan" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  // v3: late_cancel_no_show_client
  {
    id: "demo-appt-0011",
    agency_id: DEMO_AGENCY_ID,
    title: "Therapy Session",
    description: "Counseling session interpretation",
    status: "late_cancel_no_show_client",
    modality: "on_site",
    scheduled_start: dayAt(-1, 10, 0),
    scheduled_end: dayAt(-1, 11, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-1",
    interpreter_id: "demo-interp-1",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: null,
    interpreter_notes: "Waited 15 minutes. Client did not arrive.",
    agency_notes: "Late cancel fee applied — full scheduled duration.",
    interpreter_notes_history: null,
    custom_fields: { include_mileage: true, include_travel: false },
    assignment_method: "manual",
    cancellation_reason: "Client did not show up within cancellation window.",
    cancelled_at: dayAt(-1, 10, 15),
    is_self_claimable: false,
    created_at: subDays(today, 4).toISOString(),
    updated_at: dayAt(-1, 10, 15),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Spanish", code: "es" },
    interpreter: { first_name: "Carlos", last_name: "Rivera" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  // v3: no_show_interpreter
  {
    id: "demo-appt-0012",
    agency_id: DEMO_AGENCY_ID,
    title: "School Conference",
    description: "Parent-teacher conference interpretation",
    status: "no_show_interpreter",
    modality: "on_site",
    scheduled_start: dayAt(-2, 14, 0),
    scheduled_end: dayAt(-2, 15, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-3",
    location_id: "demo-loc-3",
    language_id: "demo-lang-1",
    interpreter_id: "demo-interp-5",
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: null,
    interpreter_notes: null,
    agency_notes: "Interpreter did not arrive. Non-billable. Follow up required.",
    interpreter_notes_history: null,
    custom_fields: null,
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield", state: "IL", zip_code: "62703" },
    languages: { name: "Spanish", code: "es" },
    interpreter: { first_name: "Yuki", last_name: "Tanaka" },
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
  // v3: reassignment_needed
  {
    id: "demo-appt-0013",
    agency_id: DEMO_AGENCY_ID,
    title: "Follow-Up Appointment",
    description: "Post-surgery follow-up needing reassignment",
    status: "reassignment_needed",
    modality: "on_site",
    scheduled_start: dayAt(2, 9, 0),
    scheduled_end: dayAt(2, 10, 0),
    actual_start: null,
    actual_end: null,
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-2",
    interpreter_id: null,
    requester_id: "demo-requester-id",
    notes: null,
    requester_notes: "Mandarin interpreter needed for follow-up.",
    interpreter_notes: null,
    agency_notes: "Original interpreter (Mei Wong) requested reassignment due to conflict.",
    interpreter_notes_history: [
      { interpreter_name: "Mei Wong", interpreter_id: "demo-interp-2", notes: "I have a scheduling conflict on this day. Requesting reassignment.", timestamp: subDays(today, 1).toISOString() },
    ],
    custom_fields: { include_mileage: true, include_travel: false },
    assignment_method: null,
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: true,
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "Mandarin", code: "zh" },
    interpreter: null,
    requester: { first_name: "Lisa", last_name: "Chen" },
  },
];

// ── Demo Billing Rates ──────────────────────────────────
export const demoBillingRates = [
  {
    id: "demo-rate-1",
    agency_id: DEMO_AGENCY_ID,
    name: "Standard Rate",
    customer_id: null,
    billing_model: "hourly",
    base_rate: 50,
    hourly_rate: 55,
    minimum_hours: 1,
    minimum_charge: 50,
    monthly_minimum: 0,
    travel_rate_per_mile: 0.655,
    travel_time_rate: 25,
    overtime_multiplier: 1.5,
    overtime_after_hours: 8,
    cancellation_window_hours: 24,
    cancellation_fee_percent: 100,
    is_default: true,
    same_day_threshold_hours: 24,
    same_day_fee: 25,
    same_day_multiplier: 1.25,
    after_hours_start: "18:00",
    after_hours_end: "08:00",
    after_hours_multiplier: 1.5,
    weekend_multiplier: 1.5,
    holiday_multiplier: 2,
    rounding_direction: "up",
    rounding_interval_minutes: 15,
    stack_premiums: true,
    apply_lastminute_to_travel: false,
    ignore_requested_duration: false,
    tier_config: [],
    effective_start_date: null,
    effective_end_date: null,
    created_at: subDays(today, 200).toISOString(),
    updated_at: subDays(today, 30).toISOString(),
  },
  {
    id: "demo-rate-2",
    agency_id: DEMO_AGENCY_ID,
    name: "Medical Premium",
    customer_id: "demo-cust-1",
    billing_model: "hourly",
    base_rate: 70,
    hourly_rate: 75,
    minimum_hours: 2,
    minimum_charge: 150,
    monthly_minimum: 0,
    travel_rate_per_mile: 0.655,
    travel_time_rate: 30,
    overtime_multiplier: 1.5,
    overtime_after_hours: 8,
    cancellation_window_hours: 48,
    cancellation_fee_percent: 50,
    is_default: false,
    same_day_threshold_hours: 12,
    same_day_fee: 50,
    same_day_multiplier: 1.5,
    after_hours_start: "17:00",
    after_hours_end: "07:00",
    after_hours_multiplier: 1.75,
    weekend_multiplier: 1.5,
    holiday_multiplier: 2,
    rounding_direction: "up",
    rounding_interval_minutes: 15,
    stack_premiums: true,
    apply_lastminute_to_travel: false,
    ignore_requested_duration: false,
    tier_config: [],
    effective_start_date: null,
    effective_end_date: null,
    created_at: subDays(today, 180).toISOString(),
    updated_at: subDays(today, 10).toISOString(),
  },
  {
    id: "demo-rate-3",
    agency_id: DEMO_AGENCY_ID,
    name: "Legal / Court Rate",
    customer_id: "demo-cust-2",
    billing_model: "hourly",
    base_rate: 90,
    hourly_rate: 95,
    minimum_hours: 2,
    minimum_charge: 190,
    monthly_minimum: 0,
    travel_rate_per_mile: 0.655,
    travel_time_rate: 35,
    overtime_multiplier: 2,
    overtime_after_hours: 8,
    cancellation_window_hours: 24,
    cancellation_fee_percent: 100,
    is_default: false,
    same_day_threshold_hours: 24,
    same_day_fee: 75,
    same_day_multiplier: 1.5,
    after_hours_start: "18:00",
    after_hours_end: "08:00",
    after_hours_multiplier: 1.5,
    weekend_multiplier: 2,
    holiday_multiplier: 2.5,
    rounding_direction: "up",
    rounding_interval_minutes: 15,
    stack_premiums: false,
    apply_lastminute_to_travel: false,
    ignore_requested_duration: false,
    tier_config: [],
    effective_start_date: null,
    effective_end_date: null,
    created_at: subDays(today, 150).toISOString(),
    updated_at: subDays(today, 5).toISOString(),
  },
  {
    id: "demo-rate-4",
    agency_id: DEMO_AGENCY_ID,
    name: "Education Discount",
    customer_id: "demo-cust-3",
    billing_model: "hourly",
    base_rate: 40,
    hourly_rate: 45,
    minimum_hours: 1,
    minimum_charge: 45,
    monthly_minimum: 0,
    travel_rate_per_mile: 0.5,
    travel_time_rate: 20,
    overtime_multiplier: 1.25,
    overtime_after_hours: 6,
    cancellation_window_hours: 12,
    cancellation_fee_percent: 50,
    is_default: false,
    same_day_threshold_hours: 24,
    same_day_fee: 0,
    same_day_multiplier: 1,
    after_hours_start: "18:00",
    after_hours_end: "08:00",
    after_hours_multiplier: 1.25,
    weekend_multiplier: 1.25,
    holiday_multiplier: 1.5,
    rounding_direction: "nearest",
    rounding_interval_minutes: 15,
    stack_premiums: true,
    apply_lastminute_to_travel: false,
    ignore_requested_duration: false,
    tier_config: [],
    effective_start_date: null,
    effective_end_date: null,
    created_at: subDays(today, 120).toISOString(),
    updated_at: subDays(today, 15).toISOString(),
  },
];

// ── Demo Invoices ───────────────────────────────────────
export const demoInvoices = [
  {
    id: "demo-inv-1",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-1",
    invoice_number: "INV-2026-001",
    status: "paid",
    issued_date: subDays(today, 45).toISOString().split("T")[0],
    due_date: subDays(today, 15).toISOString().split("T")[0],
    subtotal: 1125,
    tax_rate: 0,
    tax_amount: 0,
    total: 1125,
    notes: "January services – Valley Medical Center",
    created_at: subDays(today, 45).toISOString(),
    updated_at: subDays(today, 20).toISOString(),
    customers: { name: "Valley Medical Center" },
  },
  {
    id: "demo-inv-2",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-2",
    invoice_number: "INV-2026-002",
    status: "sent",
    issued_date: subDays(today, 15).toISOString().split("T")[0],
    due_date: addDays(today, 15).toISOString().split("T")[0],
    subtotal: 1900,
    tax_rate: 0,
    tax_amount: 0,
    total: 1900,
    notes: "February legal interpreting services",
    created_at: subDays(today, 15).toISOString(),
    updated_at: subDays(today, 14).toISOString(),
    customers: { name: "Johnson & Associates Law" },
  },
  {
    id: "demo-inv-3",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-3",
    invoice_number: "INV-2026-003",
    status: "draft",
    issued_date: subDays(today, 3).toISOString().split("T")[0],
    due_date: addDays(today, 27).toISOString().split("T")[0],
    subtotal: 540,
    tax_rate: 0,
    tax_amount: 0,
    total: 540,
    notes: "School district – IEP meetings & conferences",
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
    customers: { name: "City School District" },
  },
  {
    id: "demo-inv-4",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-4",
    invoice_number: "INV-2026-004",
    status: "overdue",
    issued_date: subDays(today, 60).toISOString().split("T")[0],
    due_date: subDays(today, 30).toISOString().split("T")[0],
    subtotal: 760,
    tax_rate: 0,
    tax_amount: 0,
    total: 760,
    notes: "December court hearings",
    created_at: subDays(today, 60).toISOString(),
    updated_at: subDays(today, 60).toISOString(),
    customers: { name: "County Superior Court" },
  },
  {
    id: "demo-inv-5",
    agency_id: DEMO_AGENCY_ID,
    customer_id: "demo-cust-1",
    invoice_number: "INV-2026-005",
    status: "sent",
    issued_date: subDays(today, 5).toISOString().split("T")[0],
    due_date: addDays(today, 25).toISOString().split("T")[0],
    subtotal: 825,
    tax_rate: 0,
    tax_amount: 0,
    total: 825,
    notes: "February medical interpretation",
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 5).toISOString(),
    customers: { name: "Valley Medical Center" },
  },
];

// ── Demo Invoice Line Items ─────────────────────────────
export const demoInvoiceLineItems: Record<string, any[]> = {
  "demo-inv-1": [
    { id: "demo-li-1a", invoice_id: "demo-inv-1", appointment_id: null, description: "Medical Consultation — Spanish — Carlos Rivera — Jan 10", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1b", invoice_id: "demo-inv-1", appointment_id: null, description: "Patient Intake — Vietnamese — Yuki Tanaka — Jan 12", quantity: 1.5, unit_price: 75, amount: 112.5, line_type: "service", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1c", invoice_id: "demo-inv-1", appointment_id: null, description: "Follow-up Visit — Spanish — Carlos Rivera — Jan 15", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1d", invoice_id: "demo-inv-1", appointment_id: null, description: "Travel — 42 miles", quantity: 42, unit_price: 0.655, amount: 27.51, line_type: "travel", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1e", invoice_id: "demo-inv-1", appointment_id: null, description: "Surgical Consult — Arabic — Fatima Al-Hassan — Jan 22", quantity: 3, unit_price: 75, amount: 225, line_type: "service", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1f", invoice_id: "demo-inv-1", appointment_id: null, description: "Discharge Instructions — Spanish — Carlos Rivera — Jan 28", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 45).toISOString() },
    { id: "demo-li-1g", invoice_id: "demo-inv-1", appointment_id: null, description: "Emergency Room — Mandarin — Mei Wong — Jan 30", quantity: 4, unit_price: 75, amount: 300, line_type: "service", created_at: subDays(today, 45).toISOString() },
  ],
  "demo-inv-2": [
    { id: "demo-li-2a", invoice_id: "demo-inv-2", appointment_id: null, description: "Deposition — Mandarin — Mei Wong — Feb 3", quantity: 4, unit_price: 95, amount: 380, line_type: "service", created_at: subDays(today, 15).toISOString() },
    { id: "demo-li-2b", invoice_id: "demo-inv-2", appointment_id: null, description: "Witness Interview — Russian — Andrei Volkov — Feb 7", quantity: 3, unit_price: 95, amount: 285, line_type: "service", created_at: subDays(today, 15).toISOString() },
    { id: "demo-li-2c", invoice_id: "demo-inv-2", appointment_id: null, description: "Court Hearing — Russian — Andrei Volkov — Feb 10", quantity: 5, unit_price: 95, amount: 475, line_type: "service", created_at: subDays(today, 15).toISOString() },
    { id: "demo-li-2d", invoice_id: "demo-inv-2", appointment_id: null, description: "Client Meeting — Mandarin — Mei Wong — Feb 14", quantity: 2, unit_price: 95, amount: 190, line_type: "service", created_at: subDays(today, 15).toISOString() },
    { id: "demo-li-2e", invoice_id: "demo-inv-2", appointment_id: null, description: "Travel — 85 miles", quantity: 85, unit_price: 0.655, amount: 55.68, line_type: "travel", created_at: subDays(today, 15).toISOString() },
    { id: "demo-li-2f", invoice_id: "demo-inv-2", appointment_id: null, description: "Arbitration — Japanese — Yuki Tanaka — Feb 18", quantity: 4, unit_price: 95, amount: 380, line_type: "service", created_at: subDays(today, 15).toISOString() },
  ],
  "demo-inv-3": [
    { id: "demo-li-3a", invoice_id: "demo-inv-3", appointment_id: null, description: "IEP Meeting — Arabic — Fatima Al-Hassan — Feb 20", quantity: 2, unit_price: 45, amount: 90, line_type: "service", created_at: subDays(today, 3).toISOString() },
    { id: "demo-li-3b", invoice_id: "demo-inv-3", appointment_id: null, description: "Parent-Teacher Conf — Spanish — Carlos Rivera — Feb 21", quantity: 1.5, unit_price: 45, amount: 67.5, line_type: "service", created_at: subDays(today, 3).toISOString() },
    { id: "demo-li-3c", invoice_id: "demo-inv-3", appointment_id: null, description: "Student Assessment — Vietnamese — Yuki Tanaka — Feb 22", quantity: 3, unit_price: 45, amount: 135, line_type: "service", created_at: subDays(today, 3).toISOString() },
    { id: "demo-li-3d", invoice_id: "demo-inv-3", appointment_id: null, description: "Enrollment Meeting — Spanish — Carlos Rivera — Feb 23", quantity: 2, unit_price: 45, amount: 90, line_type: "service", created_at: subDays(today, 3).toISOString() },
    { id: "demo-li-3e", invoice_id: "demo-inv-3", appointment_id: null, description: "Travel — 24 miles", quantity: 24, unit_price: 0.5, amount: 12, line_type: "travel", created_at: subDays(today, 3).toISOString() },
  ],
  "demo-inv-4": [
    { id: "demo-li-4a", invoice_id: "demo-inv-4", appointment_id: null, description: "Court Hearing — Russian — Andrei Volkov — Dec 5", quantity: 4, unit_price: 95, amount: 380, line_type: "service", created_at: subDays(today, 60).toISOString() },
    { id: "demo-li-4b", invoice_id: "demo-inv-4", appointment_id: null, description: "Arraignment — Spanish — Carlos Rivera — Dec 12", quantity: 2, unit_price: 95, amount: 190, line_type: "service", created_at: subDays(today, 60).toISOString() },
    { id: "demo-li-4c", invoice_id: "demo-inv-4", appointment_id: null, description: "Sentencing Hearing — Russian — Andrei Volkov — Dec 18", quantity: 2, unit_price: 95, amount: 190, line_type: "service", created_at: subDays(today, 60).toISOString() },
  ],
  "demo-inv-5": [
    { id: "demo-li-5a", invoice_id: "demo-inv-5", appointment_id: null, description: "ER Visit — Portuguese — Carlos Rivera — Feb 15", quantity: 3, unit_price: 75, amount: 225, line_type: "service", created_at: subDays(today, 5).toISOString() },
    { id: "demo-li-5b", invoice_id: "demo-inv-5", appointment_id: null, description: "Specialist Referral — Arabic — Fatima Al-Hassan — Feb 17", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 5).toISOString() },
    { id: "demo-li-5c", invoice_id: "demo-inv-5", appointment_id: null, description: "Lab Results Review — Spanish — Carlos Rivera — Feb 19", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 5).toISOString() },
    { id: "demo-li-5d", invoice_id: "demo-inv-5", appointment_id: null, description: "Pre-Op Consult — Mandarin — Mei Wong — Feb 21", quantity: 2, unit_price: 75, amount: 150, line_type: "service", created_at: subDays(today, 5).toISOString() },
    { id: "demo-li-5e", invoice_id: "demo-inv-5", appointment_id: null, description: "Travel — 38 miles", quantity: 38, unit_price: 0.655, amount: 24.89, line_type: "travel", created_at: subDays(today, 5).toISOString() },
  ],
};

// ── Demo Notification Log ───────────────────────────────
export const demoNotificationLog = [
  {
    id: "demo-nlog-1",
    agency_id: DEMO_AGENCY_ID,
    channel: "email",
    recipient: "carlos@interpreter.com",
    subject: "New Assignment: Medical Consultation",
    body: "Hi Carlos, you have been assigned to a Medical Consultation on " + format(today, "MMM d") + " at 8:30 AM at Valley Medical Center.",
    status: "sent",
    sent_at: subDays(today, 2).toISOString(),
    error_message: null,
    template_id: null,
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0001",
    created_at: subDays(today, 2).toISOString(),
  },
  {
    id: "demo-nlog-2",
    agency_id: DEMO_AGENCY_ID,
    channel: "sms",
    recipient: "(555) 300-0002",
    subject: null,
    body: "Reminder: Legal Deposition tomorrow at 10:00 AM. Location: Johnson & Associates – Downtown Office.",
    status: "sent",
    sent_at: subDays(today, 1).toISOString(),
    error_message: null,
    template_id: null,
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0002",
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-nlog-3",
    agency_id: DEMO_AGENCY_ID,
    channel: "email",
    recipient: "pgomez@citysd.edu",
    subject: "Invoice INV-2026-003 Ready",
    body: "Dear Patricia, your invoice INV-2026-003 for $540.00 is ready for review.",
    status: "sent",
    sent_at: subDays(today, 3).toISOString(),
    error_message: null,
    template_id: null,
    related_entity_type: "invoice",
    related_entity_id: "demo-inv-3",
    created_at: subDays(today, 3).toISOString(),
  },
  {
    id: "demo-nlog-4",
    agency_id: DEMO_AGENCY_ID,
    channel: "sms",
    recipient: "(555) 300-0004",
    subject: null,
    body: "Your Court Hearing assignment starts in 1 hour. Please arrive 15 min early for security screening.",
    status: "sent",
    sent_at: todayAt(8, 0),
    error_message: null,
    template_id: null,
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0004",
    created_at: todayAt(8, 0),
  },
  {
    id: "demo-nlog-5",
    agency_id: DEMO_AGENCY_ID,
    channel: "email",
    recipient: "yuki.tanaka@interpreter.com",
    subject: "Appointment Cancelled: Witness Interview",
    body: "Hi Yuki, the Witness Interview scheduled for " + format(subDays(today, 2), "MMM d") + " has been cancelled. Reason: Client rescheduled.",
    status: "sent",
    sent_at: subDays(today, 3).toISOString(),
    error_message: null,
    template_id: null,
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0008",
    created_at: subDays(today, 3).toISOString(),
  },
  {
    id: "demo-nlog-6",
    agency_id: DEMO_AGENCY_ID,
    channel: "email",
    recipient: "billing@valleymed.org",
    subject: "Payment Reminder: INV-2026-004",
    body: "This is a reminder that invoice INV-2026-004 for $760.00 is now overdue. Please arrange payment at your earliest convenience.",
    status: "failed",
    sent_at: null,
    error_message: "SMTP connection timeout",
    template_id: null,
    related_entity_type: "invoice",
    related_entity_id: "demo-inv-4",
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-nlog-7",
    agency_id: DEMO_AGENCY_ID,
    channel: "sms",
    recipient: "(555) 300-0001",
    subject: null,
    body: "New available job: Parent-Teacher Conference on " + format(addDays(today, 1), "MMM d") + ". Claim it in the app!",
    status: "pending",
    sent_at: null,
    error_message: null,
    template_id: null,
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0006",
    created_at: today.toISOString(),
  },
];

// ── Demo Notifications (in-app) ────────────────────────
export const demoNotifications = [
  {
    id: "demo-notif-1",
    user_id: "demo-admin-id",
    agency_id: DEMO_AGENCY_ID,
    title: "New appointment request",
    message: "Lisa Chen submitted a request for an IEP Meeting interpreter.",
    type: "appointment",
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0003",
    is_read: false,
    read_at: null,
    created_at: subDays(today, 0).toISOString(),
  },
  {
    id: "demo-notif-2",
    user_id: "demo-admin-id",
    agency_id: DEMO_AGENCY_ID,
    title: "Invoice overdue",
    message: "Invoice INV-2026-004 for County Superior Court is 30 days overdue ($760.00).",
    type: "billing",
    related_entity_type: "invoice",
    related_entity_id: "demo-inv-4",
    is_read: false,
    read_at: null,
    created_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-notif-3",
    user_id: "demo-admin-id",
    agency_id: DEMO_AGENCY_ID,
    title: "Appointment cancelled",
    message: "Witness Interview was cancelled by the client. Interpreter Yuki Tanaka has been notified.",
    type: "appointment",
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0008",
    is_read: true,
    read_at: subDays(today, 2).toISOString(),
    created_at: subDays(today, 3).toISOString(),
  },
  {
    id: "demo-notif-4",
    user_id: "demo-admin-id",
    agency_id: DEMO_AGENCY_ID,
    title: "Court Hearing in progress",
    message: "Andrei Volkov checked in for the Court Hearing at County Courthouse.",
    type: "appointment",
    related_entity_type: "appointment",
    related_entity_id: "demo-appt-0004",
    is_read: true,
    read_at: todayAt(9, 10),
    created_at: todayAt(9, 5),
  },
];

// ── Demo Time Tracking (interpreter appointments with time/mileage) ──
export const demoTimeTrackingAppointments = [
  {
    id: "demo-appt-0004",
    agency_id: DEMO_AGENCY_ID,
    title: "Court Hearing",
    status: "in_progress",
    scheduled_start: todayAt(9, 0),
    scheduled_end: todayAt(11, 0),
    actual_start: todayAt(9, 5),
    actual_end: null,
    custom_fields: { mileage: 12.5 },
    customers: { name: "County Superior Court" },
    languages: { name: "Russian" },
    created_at: subDays(today, 3).toISOString(),
    updated_at: today.toISOString(),
  },
  {
    id: "demo-appt-0005",
    agency_id: DEMO_AGENCY_ID,
    title: "Patient Intake",
    status: "completed",
    scheduled_start: dayAt(-1, 14, 0),
    scheduled_end: dayAt(-1, 15, 0),
    actual_start: dayAt(-1, 14, 5),
    actual_end: dayAt(-1, 15, 10),
    custom_fields: { mileage: 8.2 },
    customers: { name: "Valley Medical Center" },
    languages: { name: "Vietnamese" },
    created_at: subDays(today, 4).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-appt-0001",
    agency_id: DEMO_AGENCY_ID,
    title: "Medical Consultation",
    status: "interpreter_confirmed",
    scheduled_start: todayAt(8, 30),
    scheduled_end: todayAt(9, 30),
    actual_start: null,
    actual_end: null,
    custom_fields: null,
    customers: { name: "Valley Medical Center" },
    languages: { name: "Spanish" },
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
  },
  {
    id: "demo-appt-0006",
    agency_id: DEMO_AGENCY_ID,
    title: "Parent-Teacher Conference",
    status: "interpreter_confirmed",
    scheduled_start: dayAt(1, 15, 0),
    scheduled_end: dayAt(1, 16, 0),
    actual_start: null,
    actual_end: null,
    custom_fields: null,
    customers: { name: "City School District" },
    languages: { name: "Spanish" },
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
  },
];

// ── Demo Messages ──────────────────────────────────────
export const demoMessages = [
  {
    id: "demo-msg-1",
    sender: "Carlos Rivera",
    preview: "I'll be 5 minutes late to the Medical Consultation tomorrow — traffic on I-55.",
    time: subDays(today, 0).toISOString(),
    unread: true,
  },
  {
    id: "demo-msg-2",
    sender: "Lisa Chen",
    preview: "Can we add a second interpreter for the IEP meeting? The family also speaks French.",
    time: subDays(today, 1).toISOString(),
    unread: true,
  },
  {
    id: "demo-msg-3",
    sender: "Mei Wong",
    preview: "Deposition went well. I've uploaded my notes to the appointment record.",
    time: subDays(today, 2).toISOString(),
    unread: false,
  },
  {
    id: "demo-msg-4",
    sender: "Dr. Amanda Foster",
    preview: "Thank you for the prompt service. We'd like to set up a recurring weekly appointment.",
    time: subDays(today, 3).toISOString(),
    unread: false,
  },
  {
    id: "demo-msg-5",
    sender: "Andrei Volkov",
    preview: "Checked in for the court hearing. Judge Torres' courtroom is running on schedule.",
    time: todayAt(9, 2),
    unread: false,
  },
];

// ── Demo Report Appointments (6 months of data for charts) ──
function monthAgo(m: number, day: number, hour: number) {
  const d = new Date(today.getFullYear(), today.getMonth() - m, day, hour);
  return d.toISOString();
}

const reportStatuses = ["completed", "completed", "completed_last_minute", "interpreter_assigned", "cancelled", "completed", "in_progress", "late_cancel_no_show_client", "completed", "interpreter_confirmed", "requested", "no_show_interpreter", "requested_last_minute", "reassignment_needed", "completed_last_minute"] as const;
const reportLangs = [
  { name: "Spanish" }, { name: "Mandarin" }, { name: "Arabic" }, { name: "Vietnamese" },
  { name: "Russian" }, { name: "Korean" }, { name: "Spanish" }, { name: "Tagalog" },
];
const reportInterps = [
  { first_name: "María", last_name: "García" }, { first_name: "Wei", last_name: "Chen" },
  { first_name: "Fatima", last_name: "Al-Rashid" }, { first_name: "Linh", last_name: "Nguyen" },
  { first_name: "Andrei", last_name: "Volkov" },
];
const reportCustomers = [
  { name: "Valley Medical Center" }, { name: "Riverside School District" },
  { name: "Superior Court – County" }, { name: "Greenfield Community Clinic" },
];

export const demoReportAppointments: any[] = [];
let rid = 0;
for (let m = 5; m >= 0; m--) {
  const count = m === 0 ? 8 : 6 + Math.floor(Math.random() * 6);
  for (let i = 0; i < count; i++) {
    rid++;
    demoReportAppointments.push({
      id: `demo-rpt-${rid}`,
      agency_id: DEMO_AGENCY_ID,
      status: reportStatuses[rid % reportStatuses.length],
      scheduled_start: monthAgo(m, 1 + (i * 3) % 28, 8 + (i % 8)),
      languages: reportLangs[rid % reportLangs.length],
      customers: reportCustomers[rid % reportCustomers.length],
      interpreter: reportInterps[rid % reportInterps.length],
    });
  }
}

// ── Demo Interpreter: My Languages ─────────────────────
export const demoMyLanguages = [
  // Carlos Rivera: ASL + Spanish
  { id: "demo-il-1", interpreter_id: "demo-interp-1", language_id: "demo-lang-8", is_certified: true, certification_details: "RID CDI certified, NIC Advanced", languages: { name: "ASL (American Sign Language)", code: "ase" } },
  { id: "demo-il-1b", interpreter_id: "demo-interp-1", language_id: "demo-lang-1", is_certified: true, certification_details: "Court-certified Spanish", languages: { name: "Spanish", code: "es" } },
  // Mei Wong: Mandarin + Spanish
  { id: "demo-il-2", interpreter_id: "demo-interp-2", language_id: "demo-lang-2", is_certified: true, certification_details: "ATA certified", languages: { name: "Mandarin", code: "zh" } },
  { id: "demo-il-2b", interpreter_id: "demo-interp-2", language_id: "demo-lang-1", is_certified: false, certification_details: null, languages: { name: "Spanish", code: "es" } },
  // Fatima Al-Hassan: Arabic + Spanish
  { id: "demo-il-3", interpreter_id: "demo-interp-3", language_id: "demo-lang-3", is_certified: true, certification_details: "Medical Arabic certified", languages: { name: "Arabic", code: "ar" } },
  { id: "demo-il-3b", interpreter_id: "demo-interp-3", language_id: "demo-lang-1", is_certified: false, certification_details: null, languages: { name: "Spanish", code: "es" } },
  // Andrei Volkov: Russian
  { id: "demo-il-4", interpreter_id: "demo-interp-4", language_id: "demo-lang-4", is_certified: true, certification_details: "Legal Russian certified", languages: { name: "Russian", code: "ru" } },
  // Yuki Tanaka: Japanese + ASL
  { id: "demo-il-5", interpreter_id: "demo-interp-5", language_id: "demo-lang-5", is_certified: true, certification_details: "JLPT N1", languages: { name: "Japanese", code: "ja" } },
  { id: "demo-il-5b", interpreter_id: "demo-interp-5", language_id: "demo-lang-8", is_certified: false, certification_details: null, languages: { name: "ASL (American Sign Language)", code: "ase" } },
];

// ── Demo Shared Availability Blocks (for colleagues) ───
const nextMon = addDays(startOfWeek(today, { weekStartsOn: 1 }), 7);
function offsetDate(d: Date, offset: number) { return format(addDays(d, offset), "yyyy-MM-dd"); }



export const demoSharedAvailability = [
  // Mei Wong: vacation next week Mon-Wed
  { id: "demo-shared-avail-1", interpreter_id: "demo-interp-2", agency_id: DEMO_AGENCY_ID, is_recurring: false, day_of_week: null, start_time: "00:00", end_time: "23:59", specific_date: offsetDate(nextMon, 0), end_date: offsetDate(nextMon, 2), is_all_day: true, notes: "Family vacation", created_at: subDays(today, 5).toISOString() },
  // Mei Wong: recurring Friday afternoons
  { id: "demo-shared-avail-2", interpreter_id: "demo-interp-2", agency_id: DEMO_AGENCY_ID, is_recurring: true, day_of_week: 5, start_time: "13:00", end_time: "17:00", specific_date: null, end_date: null, is_all_day: false, notes: "Class", created_at: subDays(today, 30).toISOString() },
  // Fatima Al-Hassan: single day off next Thursday
  { id: "demo-shared-avail-3", interpreter_id: "demo-interp-3", agency_id: DEMO_AGENCY_ID, is_recurring: false, day_of_week: null, start_time: "00:00", end_time: "23:59", specific_date: offsetDate(nextMon, 3), end_date: null, is_all_day: true, notes: "Doctor appointment", created_at: subDays(today, 2).toISOString() },
  // Fatima Al-Hassan: recurring Wednesday mornings
  { id: "demo-shared-avail-4", interpreter_id: "demo-interp-3", agency_id: DEMO_AGENCY_ID, is_recurring: true, day_of_week: 3, start_time: "08:00", end_time: "12:00", specific_date: null, end_date: null, is_all_day: false, notes: "Training", created_at: subDays(today, 60).toISOString() },
  // Yuki Tanaka: vacation next Fri-Sat
  { id: "demo-shared-avail-5", interpreter_id: "demo-interp-5", agency_id: DEMO_AGENCY_ID, is_recurring: false, day_of_week: null, start_time: "00:00", end_time: "23:59", specific_date: offsetDate(nextMon, 4), end_date: offsetDate(nextMon, 5), is_all_day: true, notes: "Weekend trip", created_at: subDays(today, 3).toISOString() },
  // Andrei Volkov: recurring Tuesday all day
  { id: "demo-shared-avail-6", interpreter_id: "demo-interp-4", agency_id: DEMO_AGENCY_ID, is_recurring: true, day_of_week: 2, start_time: "00:00", end_time: "23:59", specific_date: null, end_date: null, is_all_day: true, notes: "Other agency work", created_at: subDays(today, 45).toISOString() },
];

// ── Demo Interpreter: My Schedule (ASL appointments) ───
export const demoMyScheduleAppointments = [
  {
    id: "demo-sched-1",
    agency_id: DEMO_AGENCY_ID,
    title: "Medical Consultation – Deaf Patient",
    status: "interpreter_confirmed",
    scheduled_start: todayAt(9, 0),
    scheduled_end: todayAt(10, 30),
    actual_start: null,
    actual_end: null,
    interpreter_id: "demo-interp-1",
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-8",
    notes: "Patient is Deaf. Ensure clear line of sight for signing.",
    custom_fields: { include_mileage: true, include_travel: false },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 3).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-sched-2",
    agency_id: DEMO_AGENCY_ID,
    title: "IEP Meeting – ASL Services",
    status: "interpreter_assigned",
    scheduled_start: todayAt(13, 0),
    scheduled_end: todayAt(14, 30),
    actual_start: null,
    actual_end: null,
    interpreter_id: "demo-interp-1",
    customer_id: "demo-cust-3",
    location_id: "demo-loc-3",
    language_id: "demo-lang-8",
    notes: "Annual IEP review. Student and parent are Deaf.",
    custom_fields: null,
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 2).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield", state: "IL", zip_code: "62703" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-sched-3",
    agency_id: DEMO_AGENCY_ID,
    title: "Court Hearing – ASL Interpretation",
    status: "interpreter_confirmed",
    scheduled_start: dayAt(1, 10, 0),
    scheduled_end: dayAt(1, 12, 0),
    actual_start: null,
    actual_end: null,
    interpreter_id: "demo-interp-1",
    customer_id: "demo-cust-4",
    location_id: "demo-loc-4",
    language_id: "demo-lang-8",
    notes: "Defendant is Deaf. Court-certified ASL interpreter required.",
    custom_fields: { include_mileage: true, include_travel: true },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 5).toISOString(),
    updated_at: subDays(today, 2).toISOString(),
    customers: { name: "County Superior Court" },
    locations: { name: "County Courthouse – Room 214", address_line1: "100 Court Square", city: "Springfield", state: "IL", zip_code: "62701" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-sched-4",
    agency_id: DEMO_AGENCY_ID,
    title: "Therapy Session – ASL",
    status: "completed",
    scheduled_start: dayAt(-1, 14, 0),
    scheduled_end: dayAt(-1, 15, 0),
    actual_start: dayAt(-1, 14, 5),
    actual_end: dayAt(-1, 15, 5),
    interpreter_id: "demo-interp-1",
    customer_id: "demo-cust-1",
    location_id: "demo-loc-1",
    language_id: "demo-lang-8",
    notes: "Completed successfully.",
    custom_fields: { include_mileage: true, mileage: 14.2, signed_at: dayAt(-1, 15, 5), signature_captured: true },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 4).toISOString(),
    updated_at: subDays(today, 1).toISOString(),
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield", state: "IL", zip_code: "62704" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-sched-5",
    agency_id: DEMO_AGENCY_ID,
    title: "Staff Meeting Accessibility",
    status: "completed",
    scheduled_start: dayAt(-3, 9, 0),
    scheduled_end: dayAt(-3, 10, 30),
    actual_start: dayAt(-3, 9, 0),
    actual_end: dayAt(-3, 10, 25),
    interpreter_id: "demo-interp-1",
    customer_id: "demo-cust-3",
    location_id: "demo-loc-3",
    language_id: "demo-lang-8",
    notes: "",
    custom_fields: { include_mileage: false, signed_at: dayAt(-3, 10, 25), signature_captured: true },
    assignment_method: "manual",
    cancellation_reason: null,
    cancelled_at: null,
    is_self_claimable: false,
    created_at: subDays(today, 6).toISOString(),
    updated_at: subDays(today, 3).toISOString(),
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield", state: "IL", zip_code: "62703" },
    languages: { name: "ASL (American Sign Language)" },
  },
];

// ── Demo Interpreter: My Earnings (completed ASL jobs this month + last) ──
export const demoMyEarningsAppointments = [
  {
    id: "demo-earn-1",
    title: "Therapy Session – ASL",
    status: "completed",
    scheduled_start: dayAt(-1, 14, 0),
    scheduled_end: dayAt(-1, 15, 0),
    actual_start: dayAt(-1, 14, 5),
    actual_end: dayAt(-1, 15, 5),
    custom_fields: { include_mileage: true, mileage: 14.2 },
    customers: { name: "Valley Medical Center" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-earn-2",
    title: "Staff Meeting Accessibility",
    status: "completed",
    scheduled_start: dayAt(-3, 9, 0),
    scheduled_end: dayAt(-3, 10, 30),
    actual_start: dayAt(-3, 9, 0),
    actual_end: dayAt(-3, 10, 25),
    custom_fields: { include_mileage: false },
    customers: { name: "City School District" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-earn-3",
    title: "ER Visit – ASL",
    status: "completed",
    scheduled_start: dayAt(-5, 18, 0),
    scheduled_end: dayAt(-5, 19, 30),
    actual_start: dayAt(-5, 18, 10),
    actual_end: dayAt(-5, 19, 40),
    custom_fields: { include_mileage: true, mileage: 22 },
    customers: { name: "Valley Medical Center" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-earn-4",
    title: "Parent Conference – ASL",
    status: "completed",
    scheduled_start: dayAt(-8, 15, 0),
    scheduled_end: dayAt(-8, 16, 0),
    actual_start: dayAt(-8, 15, 0),
    actual_end: dayAt(-8, 16, 10),
    custom_fields: { include_mileage: true, mileage: 8.5 },
    customers: { name: "City School District" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-earn-5",
    title: "Deposition – ASL",
    status: "completed",
    scheduled_start: dayAt(-12, 10, 0),
    scheduled_end: dayAt(-12, 13, 0),
    actual_start: dayAt(-12, 10, 0),
    actual_end: dayAt(-12, 13, 15),
    custom_fields: { include_mileage: true, mileage: 18 },
    customers: { name: "Johnson & Associates Law" },
    languages: { name: "ASL (American Sign Language)" },
  },
];

// ── Demo Interpreter: Available Jobs (unassigned ASL jobs) ──
export const demoAvailableJobs = [
  {
    id: "demo-avail-1",
    agency_id: DEMO_AGENCY_ID,
    title: "Audiology Follow-Up – ASL",
    description: "Patient needs ASL interpreter for post-surgery follow-up",
    status: "requested",
    scheduled_start: dayAt(2, 10, 0),
    scheduled_end: dayAt(2, 11, 0),
    interpreter_id: null,
    is_self_claimable: true,
    assignment_method: null,
    customers: { name: "Valley Medical Center" },
    locations: { name: "Valley Medical – Main Campus", address_line1: "1200 Health Blvd", city: "Springfield" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-avail-2",
    agency_id: DEMO_AGENCY_ID,
    title: "School Assembly – ASL Access",
    description: "K-5 school assembly, Deaf students attending",
    status: "requested",
    scheduled_start: dayAt(3, 9, 0),
    scheduled_end: dayAt(3, 10, 30),
    interpreter_id: null,
    is_self_claimable: true,
    assignment_method: null,
    customers: { name: "City School District" },
    locations: { name: "Lincoln Elementary School", address_line1: "850 Oak Ave", city: "Springfield" },
    languages: { name: "ASL (American Sign Language)" },
  },
  {
    id: "demo-avail-3",
    agency_id: DEMO_AGENCY_ID,
    title: "Arraignment – ASL Required",
    description: "Defendant is Deaf. Court-certified interpreter required.",
    status: "reassignment_needed",
    scheduled_start: dayAt(4, 14, 0),
    scheduled_end: dayAt(4, 16, 0),
    interpreter_id: null,
    is_self_claimable: false,
    assignment_method: null,
    customers: { name: "County Superior Court" },
    locations: { name: "County Courthouse – Room 214", address_line1: "100 Court Square", city: "Springfield" },
    languages: { name: "ASL (American Sign Language)" },
  },
];
