export const ROUTES = {
  dashboard: "/dashboard",
  appointments: "/appointments",
  customers: "/customers",
  interpreters: "/interpreters",
  billingRates: "/billing-rates",
  invoices: "/invoices",
  messages: "/messages",
  settings: "/settings",
  request: "/request",
  myRequests: "/my-requests",
  mySchedule: "/my-schedule",
  myEarnings: "/my-earnings",
  availability: "/availability",
  availableJobs: "/available-jobs",
  timeTracking: "/time-tracking",
  myLanguages: "/my-languages",
  reports: "/reports",
  auditLog: "/audit-log",
  regions: "/regions",
  notificationTemplates: "/notification-templates",
  notificationLog: "/notification-log",
  calendarSettings: "/calendar-settings",
  import: "/import",
  interpreterPay: "/interpreter-pay",
  customerBilling: "/customer-billing",
} as const;
